component_depth: 1
languages:
- java
exclude:
- ./assembly/.*
- ./build-tools/.*
- ./build-tools/cayenne-regression-profiler/.*
- ./build-tools/maven-cayenne-build-plugin/.*
- ./build-tools/maven-cayenne-doc-plugin/.*
- ./docs/.*
- ./docs/doc/.*
- ./eclipse/.*
- ./eclipse/cayenne3.0/.*
- ./eclipse/cayenne3.0/RemoteSystemsTempFiles/.*
- ./eclipse/cayenne3.0/inheritance-test/.*
- ./eclipse/cayenne3.0/inheritance-test/bin/.*
- ./eclipse/cayenne3.0/inheritance-test/bin/test/.*
- ./eclipse/cayenne3.0/inheritance-test/bin/test/auto/.*
- ./eclipse/cayenne3.1/.*
- ./eclipse/cayenne3.1/RemoteSystemsTempFiles/.*
- ./eclipse/cayenne3.1/cay-1468/.*
- ./eclipse/cayenne3.1/cay-1468/bin/.*
- ./eclipse/cayenne3.1/cay-1468/bin/test/.*
- ./eclipse/cayenne3.1/cay-1468/bin/test/auto/.*
- ./eclipse/lib/.*
- ./framework/.*
- ./framework/cayenne-agent/.*
- ./framework/cayenne-client/.*
- ./framework/cayenne-jdk1.5-unpublished/.*
- ./framework/cayenne-jdk1.6-unpublished/.*
- ./framework/cayenne-jpa-unpublished/.*
- ./framework/cayenne-legal-unpublished/.*
- ./framework/cayenne-modeler/.*
- ./framework/cayenne-server/.*
- ./framework/cayenne-tools/.*
- ./framework/maven-cayenne-modeler-plugin/.*
- ./framework/maven-cayenne-plugin/.*
- ./itests/.*
- ./itests/bin/.*
- ./itests/bin/org/.*
- ./itests/bin/org/apache/.*
- ./itests/bin/org/apache/cayenne/.*
- ./itests/bin/org/apache/cayenne/itest/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/auto/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/conf/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/defaults/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/defaults/auto/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/defaults/client/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/defaults/client/auto/.*
- ./itests/bin/org/apache/cayenne/itest/cpa/exp/.*
- ./itests/bin/org/apache/cayenne/itest/jpa/.*
- ./itests/bin/org/apache/cayenne/itest/pojo/.*
- ./itests/bin/org/apache/cayenne/jpa/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch2/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch2/entity/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch3/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch3/entity/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch4/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch4/entity/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch5/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch5/entity/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch6/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch6/entity/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch9/.*
- ./itests/bin/org/apache/cayenne/jpa/itest/ch9/entity/.*
- ./itests/cayenne-api/.*
- ./itests/itest-common/.*
- ./itests/jpa-chapter2/.*
- ./itests/jpa-chapter3/.*
- ./itests/jpa-chapter4/.*
- ./itests/jpa-chapter5/.*
- ./itests/jpa-chapter6/.*
- ./itests/jpa-chapter9/.*
- ./itests/lib/.*
- ./itests/pojo/.*
- ./lib/.*
- ./modeler/.*
- ./modeler/bin/.*
- ./modeler/bin/org/.*
- ./modeler/bin/org/apache/.*
- ./modeler/bin/org/apache/cayenne/.*
- ./modeler/bin/org/apache/cayenne/modeler/.*
- ./modeler/cayenne-modeler-java/.*
- ./modeler/cayenne-modeler-mac/.*
- ./modeler/cayenne-modeler-mac-ext/.*
- ./modeler/cayenne-modeler-win/.*
- ./modeler/lib/.*
- ./tutorials/.*
- ./tutorials/bin/.*
- ./tutorials/bin/org/.*
- ./tutorials/bin/org/apache/.*
- ./tutorials/bin/org/apache/cayenne/.*
- ./tutorials/bin/org/apache/cayenne/tutorial/.*
- ./tutorials/bin/org/apache/cayenne/tutorial/persistent/.*
- ./tutorials/bin/org/apache/cayenne/tutorial/persistent/client/.*
- ./tutorials/bin/org/apache/cayenne/tutorial/persistent/client/auto/.*
- ./tutorials/lib/.*
- ./tutorials/tutorial/.*
- ./tutorials/tutorial-rop-client/.*
- ./tutorials/tutorial-rop-server/.*
